Dev
YuraFesun/PosterProject pull request #1
Opened 2022-10-19 15:43 UTC by YuraFesun

Create ParcerClass

2022-10-19 17:27 UTC, AndrewPolishchuc requested changes
Need to complete your csv file

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +        String splitBy = ",";
hardcode

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +    public static void parceCSV() {
void?

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +            BufferedReader br = new BufferedReader(new FileReader(".idea/DataIn.csv"));
hardcode

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +            e.printStackTrace();
Exception handling?

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +        try {
Use try with resources

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +            while ((line = br.readLine()) != null)   //check are we have a next line
Delete comments before push code

2022-10-19 17:27 UTC, AndrewPolishchuc commented on src/main/java/DataReading/ParserCSV.java
> +                String[] ivents = line.split(splitBy);    // use comma as separator
The same

2022-10-20 10:57 UTC, YuraFesun commented on src/main/java/DataReading/ParserCSV.java
> +    public static void parceCSV() {
My bad

2022-10-20 10:58 UTC, YuraFesun commented on src/main/java/DataReading/ParserCSV.java
> +            BufferedReader br = new BufferedReader(new FileReader(".idea/DataIn.csv"));
gewh

2022-10-20 10:58 UTC, YuraFesun commented on src/main/java/DataReading/ParserCSV.java
> +            e.printStackTrace();
eggg

2022-10-20 10:59 UTC, YuraFesun commented on src/main/java/DataReading/ParserCSV.java
> +            e.printStackTrace();
Changed

2022-10-20 11:01 UTC, YuraFesun commented on src/main/java/DataReading/ParserCSV.java
> +            e.printStackTrace();
Changed

2022-10-20 11:55 UTC, AndrewPolishchuc approved these changes

2022-10-20 11:58 UTC, merged