Create a models
YuraFesun/PosterProject pull request #2
Opened 2022-10-20 14:59 UTC by YuraFesun

Create a models: EventType, Event, Storage, ActionType

2022-10-20 15:18 UTC, AndrewPolishchuc requested changes

2022-10-20 15:18 UTC, AndrewPolishchuc commented on src/main/java/Model/Event.java
> +    private Date date;
mb LocalDateTime?

2022-10-20 15:18 UTC, AndrewPolishchuc commented on src/main/java/Model/Storage.java
> +    private LinkedList<Event> eventList;
Why u use LinkedList?

2022-10-20 15:25 UTC, YuraFesun commented on src/main/java/Model/Event.java
> +    private Date date;
Yes, sorry

2022-10-20 16:47 UTC, AndrewPolishchuc requested changes

2022-10-20 16:47 UTC, AndrewPolishchuc commented on src/main/java/Model/Storage.java
> +    private HashMap<String,Event> eventList;
private HashMap<String, Event> eventList;

2022-10-20 17:04 UTC, AndrewPolishchuc commented on src/main/java/Model/Storage.java
> +    private HashMap<String,Event> eventList;
how many events can there be with the same name and different dates?

2022-10-20 17:05 UTC, AndrewPolishchuc commented on src/main/java/Model/Storage.java
> +    private HashMap<String,Event> eventList;
You should use a different structure for map value

2022-10-21 07:54 UTC, AndrewPolishchuc approved these changes

2022-10-21 07:57 UTC, merged